<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
const router = useRouter(); const recipient = ref(''); const copied = ref(false)
async function copyLink() { await navigator.clipboard?.writeText('aewol.app/invite/8f2c91'); copied.value = true }
</script>
<template><main class="invite screen"><div class="grabber"></div><button class="back" type="button" @click="router.back()">‹</button><h1>가족 초대하기</h1><p class="sub">함께 돌보는 가족을 초대해 지갑을 공유해요</p><label for="recipient">이메일 또는 전화번호</label><input id="recipient" v-model="recipient" placeholder="example@aewol.com"/><button class="primary" type="button" :disabled="!recipient.trim()">초대 보내기</button><div class="or">또는 링크로 초대</div><div class="link-row"><span>aewol.app/invite/8f2c91</span><button type="button" @click="copyLink">{{ copied ? '복사됨' : '복사' }}</button></div></main></template>
<style scoped>
.screen { position: relative; width: min(100%, 390px); min-height: 460px; margin: 0 auto; padding: 44px 22px; box-sizing: border-box; color: #1b2a49; background: #fff; border-radius: 32px; }.grabber { position: absolute; top: 14px; left: calc(50% - 20px); width: 40px; height: 5px; border-radius: 4px; background: #eaeae4; }.back { position: absolute; top: 38px; left: 18px; border: 0; background: none; color: #1b2a49; font-size: 30px; cursor: pointer; }.screen h1 { margin: 0; font-size: 18px; }.sub { margin: 7px 0 36px; color: #8a93a6; font-size: 12.5px; }.screen label { display: block; margin-bottom: 8px; color: #4a5a7d; font-size: 12.5px; font-weight: 700; }.screen input { width: 100%; height: 46px; padding: 0 14px; box-sizing: border-box; border: 1px solid #eaeae4; border-radius: 12px; background: #fafaf8; font: 13px Inter, sans-serif; }.primary { width: 100%; height: 52px; margin-top: 16px; border: 0; border-radius: 16px; background: #1b2a49; color: #fff; font-weight: 700; cursor: pointer; }.primary:disabled { opacity: .45; }.or { position: relative; margin: 66px 0 26px; border-top: 1px solid #eaeae4; text-align: center; color: #8a93a6; font-size: 11.5px; }.or::before { content: '또는 링크로 초대'; position: relative; top: -9px; padding: 0 8px; background: #fff; }.link-row { display: flex; gap: 16px; }.link-row span { flex: 1; height: 46px; padding: 14px; box-sizing: border-box; border: 1px solid #eaeae4; border-radius: 12px; background: #fafaf8; color: #4a5a7d; font-size: 12.5px; }.link-row button { width: 80px; border: 0; border-radius: 12px; background: #f2b853; color: #1b2a49; font-weight: 700; cursor: pointer; }
</style>
